arb-dir: locales/values
template-arb-file: main_en.arb
output-class: AppLocalizations
output-localization-file: app_localizations.dart
output-dir: lib/generated/locale/
required-resource-attributes: false
include-file:
  - locales/values/tabs_en.arb
#use-escaping: true