arb-dir: locale
template-arb-file: finance_ru.arb
output-class: FeatureFinanceLocalizations
output-localization-file: app_localizations.dart
output-dir: lib/src/generated/locales/
synthetic-package: false
required-resource-attributes: false
#use-escaping: true