arb-dir: locale
template-arb-file: favorites_ru.arb
output-class: FeatureFavoritesLocalizations
output-localization-file: app_localizations.dart
output-dir: lib/src/generated/locales/
required-resource-attributes: false
